-- -----------------------------------------------------
-- 1. Creación del Esquema (DDL) con USER_ID como INT
-- -----------------------------------------------------

-- Tabla de Usuarios
CREATE TABLE IF NOT EXISTS USERS
(
    ID         UUID PRIMARY KEY,

    NAME       VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD   VARCHAR(255) NOT NULL,

    -- Campos de auditoría
    CREATED    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ISACTIVE   BOOLEAN   DEFAULT TRUE,
    TOKEN      UUID         NOT NULL
);

-- Tabla de Teléfonos
CREATE TABLE IF NOT EXISTS PHONES
(
    ID           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- USER_ID debe ser INT para coincidir con USERS.ID
    USER_ID      UUID        NOT NULL,

    NUMBER       VARCHAR(20) NOT NULL,
    CITY_CODE    VARCHAR(10),
    COUNTRY_CODE VARCHAR(10),

    -- Definición de la llave foránea
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);